
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "40733354e3d71277a6ee76e7d97d568efae70136",
 "version": "4.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
