# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['autotranscribe.py'],
             pathex=['G:\\transcription'],
             binaries=[],
             datas=[
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\tqdm', 'tqdm\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\tqdm-4.61.1.dist-info', 'tqdm-4.61.1.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\regex', 'regex\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\regex-2021.4.4.dist-info', 'regex-2021.4.4.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\sacremoses', 'sacremoses\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\sacremoses-0.0.45.dist-info', 'sacremoses-0.0.45.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\requests', 'requests\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\requests-2.25.1.dist-info', 'requests-2.25.1.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\packaging', 'packaging\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\packaging-20.9.dist-info', 'packaging-20.9.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\altgraph', 'altgraph\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\altgraph-0.17.dist-info', 'altgraph-0.17.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\certifi', 'certifi\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\certifi-2021.5.30.dist-info', 'certifi-2021.5.30.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\cffi', 'cffi\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\cffi-1.14.5.dist-info', 'cffi-1.14.5.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\chardet', 'chardet\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\chardet-4.0.0.dist-info', 'chardet-4.0.0.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\click', 'click\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\click-8.0.1.dist-info', 'click-8.0.1.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\colorama', 'colorama\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\colorama-0.4.4.dist-info', 'colorama-0.4.4.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\future', 'future\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\future-0.18.2.dist-info', 'future-0.18.2.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\huggingface_hub', 'huggingface_hub\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\huggingface_hub-0.0.8.dist-info', 'huggingface_hub-0.0.8.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\idna', 'idna\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\idna-2.10.dist-info', 'idna-2.10.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\joblib', 'joblib\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\joblib-1.0.1.dist-info', 'joblib-1.0.1.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\filelock-3.0.12.dist-info', 'filelock-3.0.12.dist-info\\'),

             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\numpy', 'numpy\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\numpy-1.19.5.dist-info', 'numpy-1.19.5.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\dataclasses-0.8.dist-info', 'dataclasses-0.8.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\importlib_metadata-4.5.0.dist-info', 'importlib_metadata-4.5.0.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\pip-21.1.2.dist-info', 'pip-21.1.2.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\pycparser-2.20.dist-info', 'pycparser-2.20.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\tokenizers-0.10.3.dist-info', 'tokenizers-0.10.3.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\typing_extensions-3.10.0.0.dist-info', 'typing_extensions-3.10.0.0.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\urllib3-1.26.5.dist-info', 'urllib3-1.26.5.dist-info\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\torch', 'torch\\'),
             ('G:\\transcription\\envCompileTranscript\\Lib\\site-packages\\torch-1.9.0.dist-info', 'torch-1.9.0.dist-info\\'),

             ],
             hiddenimports=['tqdm'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='autotranscribe',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
