
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "37b5a806f69282b2088271b13888c7b37129583b",
 "version": "3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
