
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c1d8df8a4788fa40cea3cb7355bc669d9b448812",
 "version": "1.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
